# This workflow will be run on every release
name: Desktop Build

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Add your build steps here...

      - name: Upload bundles
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./src-tauri/target/release/bundle/**

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          files: ./src-tauri/target/release/bundle/**
